# Get comments by postId
GET http://localhost:5000/api/comment/6694de685e80eb615ac9f6e8
Accept: application/json


### Post a new comment
POST http://localhost:5000/api/comment
Content-Type: application/json

{
    "comment_user": "keren👍",
    "postId": "6694de685e80eb615ac9f6e8"
}

###
POST http://localhost:5000/api/subscription
Content-Type: application/json

{
    "email_subscription": "john.doe@example.com",
    "whats_app_subscription": "+1234567890"
}

###
GET http://localhost:5000/api/post/mengenal-sistem-operasi-so


###
GET http://localhost:5000/api/voice


###
GET http://localhost:5000/api/comment/count/6694de685e80eb615ac9f6e8